export const placeholderTools = [
    {
    id: 2,
    title: "Laminadora en frío 650mm",
    description: "Máquina Laminadora en Frío",
    image: "/images/herramientas/laminadora1000.webp",
    specs: ["Ancho máximo de laminación 650mm"],
    Precio_unidad: 3000,
    CantXcaja: 1,
    details: {
      zoom: "/images/herramientas/laminadora1000.webp",
    },
  },
  {
    id: 3,
    title: "Laminadora en frío 750mm",
    description: "Máquina Laminadora en Frío",
    image: "/images/herramientas/laminadora650.webp",
    specs: ["Ancho máximo de laminación 750mm"],
    Precio_unidad: 3500,
    CantXcaja: 1,
    details: {
      zoom: "/images/herramientas/laminadora650.webp",
    },
  },
  {
    id: 4,
    title: "Laminadora en frío 1000mm",
    description: "Máquina Laminadora en Frío",
    image: "/images/herramientas/laminadora1000.webp",
    specs: ["Ancho máximo de laminación 10000mm"],
    Precio_unidad: 7000,
    CantXcaja: 1,
    details: {
      zoom: "/images/herramientas/laminadora1000.webp",
    },
  },
  {
    id: 6,
    title: "Engrapadora",
    description: "V-nailer, marco de imagen neumático, Joiner.",
    image: "/images/herramientas/VnailerVerde.webp",
    specs: ["Impulsa clavos en V de 7mm a 15mm", "Tiene capacidad para 200 piezas de clavos", "Solo 2,5 kg de peso"],
    Precio_unidad: 5000,
    CantXcaja: 1,
    details: {
      zoom: "/images/herramientas/VnailerVerde.webp",
    },
  },
  {
    id: 7,
    title: "Grapas flexipunta",
    description: "Grapa flexipunta",
    image: "/images/grapas/1.webp",
    specs: ["Caja con 4300 grapas", "Grapa para ensambladora de marcos", "Garantía del vendedor: 1 mes"],
    Precio_unidad: 550,
    CantXcaja: 10,
    details: {
      zoom: "/images/grapas/1.webp",
    },
  },
  {
    id: 8,
    title: "Grapas 7mm",
    description: "Grapa encolada de 7mm",
    image: "/images/grapas/2.webp",
    specs: ["Caja con 4300 grapas", "Grapa para ensambladora de marcos", "Garantía del vendedor: 1 mes"],
    Precio_unidad: 275,
    CantXcaja: 10,
    details: {
      zoom: "/images/grapas/2.webp",
    },
  },
  {
    id: 9,
    title: "Grapas 10mm",
    description: "Grapa encolada de 10mm",
    image: "/images/grapas/2.webp",
    specs: ["Caja con 4300 grapas", "Grapa para ensambladora de marcos", "Garantía del vendedor: 1 mes"],
    Precio_unidad: 275,
    CantXcaja: 10,
    details: {
      zoom: "/images/grapas/2.webp",
    },
  },
  {
    id: 10,
    title: "Grapas 12mm",
    description: "Grapa encolada de 12mm",
    image: "/images/grapas/2.webp",
    specs: ["Caja con 4300 grapas", "Grapa para ensambladora de marcos", "Garantía del vendedor: 1 mes"],
    Precio_unidad:275,
    CantXcaja: 10,
    details: {
      zoom: "/images/grapas/2.webp",
    },
  },
  {
    id: 11,
    title: "MDF",
    description: "Macocel para enmarcado",
    image: "/images/grapas/MDF.webp",
    specs: ["Medidas: 8'x10', 11'x14', 16'x20', 20'x24', 60'x90'.","Precios desde 10 hasta 70 MXN","Personalizable", "Fácil instalación", "Resistente al tiempo"],
    Precio_unidad: 40,
    CantXcaja: 1,
    details: {
      zoom: "/images/grapas/MDF.webp",
    },
  },

  {
    id: 12,
    title: "Caballete",
    description: "Caballete Pequeño",
    image: "/images/grapas/caballetepe.webp",
    specs: ["5.9inch 15cm de altura", "Tablero de fibra de madera"],
    Precio_unidad: 300,
    CantXcaja: 2,
    details: {
      zoom: "/images/grapas/caballetepe.webp",
    },
  },
  {
    id: 13,
    title: "Caballete",
    description: "Caballete Mediano",
    image: "/images/grapas/caballetemed.webp",
    specs: ["20inch 50.8cm de altura", "Tablero de madera"],
    Precio_unidad: 400,
    CantXcaja: 2,
    details: {
      zoom: "/images/grapas/caballetemed.webp",
    },
  },
  {
    id: 14,
    title: "Caballete",
    description: "Caballete Grande",
    image: "/images/grapas/caballetegran.webp",
    specs: ["59inch 150cm de altura", "Tablero de madera"],
    Precio_unidad: 500,
    CantXcaja: 1,
    details: {
      zoom: "/images/grapas/caballetegran.webp",
    },
  },
  {
    id: 15,
    title: "Cinta Adhesiva Doble Cara Más Adhesivo",
    description: "Cinta adhesiva doble cara",
    image: "/images/grapas/cintadoblecara.webp",
    specs: ["Rollo un 25'x40m"],
    Precio_unidad: 1300,
    CantXcaja: 1,
    details: {
      zoom: "/images/grapas/cintadoblecara.webp",
    },
  },
  {
    id: 16,
    title: "Cinta Adhesiva Doble Cara Más Adhesivo",
    description: "Cinta adhesiva doble cara",
    image: "/images/grapas/cintadoblecara.webp",
    specs: ["Rollo un 50'x40m"],
    Precio_unidad: 2600,
    CantXcaja: 1,
    details: {
      zoom: "/images/grapas/cintadoblecara.webp",
    },
  },
  {
    id: 17,
    title: "Rollo de Textura Piel",
    description: "Rollo de Textura Piel Más Adhesivo",
    image: "/images/herramientas/txt-ejemplo.webp",
    specs: ["Rollo un 25'x40m"],
    Precio_unidad: 1300,
    CantXcaja: 1,
    details: {
      zoom: "/images/detalles/piel.JPG",
      zoom_detalle: "/images/detalles/pieldetalle.JPG",
    },
  },
  {
    id: 18,
    title: "Rollo de Textura Lino Fino",
    description: "Rollo de Textura Lino Fino Más Adhesivo",
    image: "/images/herramientas/txt-ejemplo.webp",
    specs: ["Rollo un 25'x40m"],
    Precio_unidad: 1300,
    CantXcaja: 1,
    details: {
      zoom: "/images/detalles/linofino.JPG",
      zoom_detalle: "/images/detalles/linofinodetalle.JPG",
    },
  },
  {
    id: 19,
    title: "Rollo de Textura Santex",
    description: "Rollo de Textura Santex Más Adhesivo",
    image: "/images/herramientas/txt-ejemplo.webp",
    specs: ["Rollo un 25'x40m"],
    Precio_unidad: 1300,
    CantXcaja: 1,
    details: {
      zoom: "/images/detalles/santex.JPG",
      zoom_detalle: "/images/detalles/santexdetalle.JPG",
    },
  },
  {
    id: 20,
    title: "Rollo de Textura Canvas",
    description: "Rollo de Textura Canvas Más Adhesivo",
    image: "/images/herramientas/txt-ejemplo.webp",
    specs: ["Rollo un 25'x40m"],
    Precio_unidad: 1300,
    CantXcaja: 1,
    details: {
      zoom: "/images/detalles/canvas.JPG",
      zoom_detalle: "/images/detalles/canvasdetalle.JPG",
    },
  },  {
    id: 21,
    title: "Rollo de Textura Piel",
    description: "Rollo de Textura Piel Más Adhesivo",
    image: "/images/herramientas/txt-ejemplo.webp",
    specs: ["Rollo un 50'x40m"],
    Precio_unidad: 2600,
    CantXcaja: 1,
    details: {
      zoom: "/images/detalles/piel.JPG",
      zoom_detalle: "/images/detalles/pieldetalle.JPG",
    },
  },
  {
    id: 22,
    title: "Rollo de Textura Lino Fino",
    description: "Rollo de Textura Lino Fino Más Adhesivo",
    image: "/images/herramientas/txt-ejemplo.webp",
    specs: ["Rollo un 50'x40m"],
    Precio_unidad: 2600,
    CantXcaja: 1,
    details: {
      zoom: "/images/detalles/linofino.JPG",
      zoom_detalle: "/images/detalles/linofinodetalle.JPG",
    },
  },
  {
    id: 23,
    title: "Rollo de Textura Santex",
    description: "Rollo de Textura Santex Más Adhesivo",
    image: "/images/herramientas/txt-ejemplo.webp",
    specs: ["Rollo un 50'x40m"],
    Precio_unidad: 2600,
    CantXcaja: 1,
    details: {
      zoom: "/images/detalles/santex.JPG",
      zoom_detalle: "/images/detalles/santexdetalle.JPG",
    },
  },
  {
    id: 24,
    title: "Rollo de Textura Canvas",
    description: "Rollo de Textura Canvas Más Adhesivo",
    image: "/images/herramientas/txt-ejemplo.webp",
    specs: ["Rollo un 50'x40m"],
    Precio_unidad: 2600,
    CantXcaja: 1,
    details: {
      zoom: "/images/detalles/canvas.JPG",
      zoom_detalle: "/images/detalles/canvasdetalle.JPG",
    },
  },
]

export const products = [
  {
    id: 25,
    title: "Romana",
    description: "Moldura Exclusiva de Romana Centro",
    image: "/images/molduras/romana.webp",
    specs: ["Colores: Vino, Nogal, Plata, Oro, Oro 89", "Cortada a medida", "Barra entera (2.9m)", "Poliestireno"],
    Precio_unidad: 120,
    CantXcaja: 20,
    details: {
      vino: "/images/detalles/romanavino.webp",
      vino_detalle: "/images/detalles/romanavinodetalle.webp",
      nogal: "/images/detalles/romananogal.webp",
      nogal_detalle: "/images/detalles/romananogaldetalle.webp",
      plata: "/images/detalles/romanaplata.webp",
      plata_detalle: "/images/detalles/romanaplatadetalle.webp",
      oro: "/images/detalles/romanaoro.webp",
      oro_detalle: "/images/detalles/romanaorodetalle.webp",
      oro89: "/images/detalles/romanaoro89.webp",
      oro89_detalle: "/images/detalles/romanaoro89detalle.webp",
    },
  },
  {
    id: 26,
    title: "florencia",
    description: "Moldura para enmarcado de alta resistencia",
    image: "/images/molduras/florencia.JPG",
    specs: ["Colores: Plata, Vino, Nogal, Cobre, Titanio ", "Cortada a medida", "Barra entera (2.9m)", "Poliestireno"],
    Precio_unidad: 120,
    CantXcaja: 17,
    details: {
      vino: "/images/detalles/florenciavino.webp",
      vino_detalle: "/images/detalles/florenciavinodetalle.webp",
      nogal: "/images/detalles/florencianogal.webp",
      nogal_detalle: "/images/detalles/florencianogaldetalle.webp",
      cobre: "/images/detalles/florenciacobre.webp",
      cobre_detalle: "/images/detalles/florenciacobredetalle.webp",
      titanio: "/images/detalles/florenciatitanio.webp",
      titanio_detalle: "/images/detalles/florenciatitaniodetalle.webp",
      plata: "/images/detalles/florenciaplata.webp",
      plata_detalle: "/images/detalles/florenciaplatadetalle.webp",
    },
  },
  {
    id: 27,
    title: "Nápoles",
    description: "Moldura para enmarcado de alta resistencia",
    image: "/images/molduras/napoles.webp",
    specs: ["Colores: Negro, Chocolate, Vino, Nogal,Titanio", "Barra entera (2.9m)", "Poliestireno"],
    Precio_unidad: 120,
    CantXcaja: 24,
    details: {
      negro: "/images/detalles/napolesnegro.webp",
      negro_detalle: "/images/detalles/napolesnegrodetalle.webp",
      chocolate: "/images/detalles/napoleschocolate.webp",
      chocolate_detalle: "/images/detalles/napoleschocolatedetalle.webp",
      vino: "/images/detalles/napolesvino.webp",
      vino_detalle: "/images/detalles/napolesvinodetalle.webp",
      nogal: "/images/detalles/napolesnogal.webp",
      nogal_detalle: "/images/detalles/napolesnogaldetalle.webp",
      titanio: "/images/detalles/napolestitanio.webp",
      titanio_detalle: "/images/detalles/napolestitaniodetalle.webp",
    },
  },
  {
    id: 28,
    title: "Milán",
    description: "Moldura para enmarcado de alta resistencia",
    image: "/images/molduras/milan.webp",
    specs: ["Colores: Negro, Plata, Bronce", "Barra entera (2.9m)", "Poliestireno"],
    Precio_unidad: 100,
    CantXcaja: 34,
    details: {
      negro: "/images/detalles/milannegro.webp",
      negro_detalle: "/images/detalles/milannegrodetalle.webp",
      plata: "/images/detalles/milanplata.webp",
      plata_detalle: "/images/detalles/milanplatadetalle.webp",
      bronce: "/images/detalles/milanbronce.webp",
      bronce_detalle: "/images/detalles/milanbroncedetalle.webp",
    },
  },
  {
    id: 29,
    title: "Lazio",
    description: "Moldura para enmarcado de alta resistencia",
    image: "/images/molduras/Lazio.jpg",
    specs: ["Colores: Negro, Plata, Chocolate, Nogal, Oro", "Cortada a medida", "Barra entera (2.9m)", "Poliestireno"],
    Precio_unidad: 55,
    CantXcaja: 100,
    details: {
      nogaloscuro: "/images/detalles/Laziodetallenogaloscuro.jpg",
      nogal: "/images/detalles/Laziodetallenogall.jpg",
      negro: "/images/detalles/Laziodetallenegro.jpg",
      oro: "/images/detalles/Laziodetalleoro.jpg",
      plata: "/images/detalles/Laziodetalleplata.jpg",
    },
  },
]

export const espejos = [
  {
    id: 22,
    title: "Espejo dorado y moderno",
    description: "Espejo dorado y moderno con diseño minimalista.",
    specs: ["Espejo dorado y moderno", "Diseño minimalista."],
    Precio_unidad: 60,
    CantXcaja: null,
    image: "/images/Espejos/1.webp",
    details: {
      zoom: "/images/Espejos/1.webp",
    },
  },
  {
    id: 23,
    title: "Espejo dorado",
    description: "Espejo dorado con marco contemporáneo.",
    specs: ["Espejo dorado con marco contemporáneo."],
    Precio_unidad: 60,
    CantXcaja: null,
    image: "/images/Espejos/2.webp",
    details: {
      zoom: "/images/Espejos/2.webp",
    },
  },
  {
    id: 24,
    title: "Espejo dorado",
    description: "Espejo dorado ideal para ambientes modernos.",
    specs: ["Espejo dorado", "Ideal para ambientes modernos."],
    Precio_unidad: 60,
    CantXcaja: null,
    image: "/images/Espejos/3.webp",
    details: {
      zoom: "/images/Espejos/3.webp",
    },
  },
  {
    id: 25,
    title: "Espejo dorado",
    description: "Diseño moderno en espejo dorado.",
    specs: ["Diseño moderno en espejo dorado", "Elegante y sutil."],
    Precio_unidad: 60,
    CantXcaja: null,
    image: "/images/Espejos/4.webp",
    details: {
      zoom: "/images/Espejos/4.webp",
    },
  },
  {
    id: 26,
    title: "Espejo dorado",
    description: "Espejo dorado con acabado brillante.",
    specs: ["Espejo dorado con acabado brillante."],
    Precio_unidad: 60,
    CantXcaja: null,
    image: "/images/Espejos/5.webp",
    details: {
      zoom: "/images/Espejos/5.webp",
    },
  },
]

export const articulosreligiosos = [
  // Primeros 7
  {
    id: 27,
    title: "Virgen de Guadalupe",
    description: "Virgen maternal, consuelo y fe en México.",
    image: "/images/terminados/1.webp",
    specs: [
      "Molduras ornamentadas  con elegante detalle.",
      "Dimensiones: 7 x 16 cm",
      "Corte con láser.",
      "Materiales premium",
    ],
    details: {
      cuadro: "/images/terminados/1.webp",
    },
  },
  {
    id: 28,
    title: "La última cena",
    description: "Comida final, preludio de redención y comunión.",
    image: "/images/terminados/2.webp",
    specs: ["Marco de Venecia oro.", "Dimensiones: 25 x 35.5 cm", "Personalización disponible", "Materiales premium"],
    details: {
      cuadro: "/images/terminados/2.webp",
    },
  },
  {
    id: 29,
    title: "Virgen de Guadalupe",
    description: "Virgen Sagrado Corazón.",
    image: "/images/terminados/3.webp",
    specs: ["Marco de Venecia oro.", "Dimensiones: 25 x 35.5 cm", "Personalización disponible", "Materiales premium"],
    details: {
      cuadro: "/images/terminados/3.webp",
    },
  },
  {
    id: 30,
    title: "La Sagrada Familia",
    description: "Familia divina, unión y amor sagrado eterno..",
    image: "/images/terminados/4.webp",
    specs: ["Marco de Venecia oro.", "Dimensiones: 25 x 35.5 cm", "Personalización disponible", "Materiales premium"],
    details: {
      cuadro: "/images/terminados/4.webp",
    },
  },
  {
    id: 31,
    title: "María y Jesús",
    description: "Amor maternal y divino en tierno encuentro.",
    details: "",
    image: "/images/terminados/5.webp",
    specs: ["Marco de Venecia oro.", "Dimensiones: 25 x 35.5 cm", "Personalización disponible", "Materiales premium"], // eslint-disable-next-line
    details: {
      cuadro: "/images/terminados/5.webp",
    },
  },
  {
    id: 32,
    title: "Virgen de Guadalupe",
    description: "Encarnación de fe y esperanza mexicana",
    image: "/images/terminados/6.webp",
    specs: [
      "Molduras ornamentadas con elegante detalle.",
      "Dimensiones: 7 x 16 cm",
      "Corte con láser.",
      "Materiales premium",
    ],
    details: {
      cuadro: "/images/terminados/6.webp",
    },
  },
  {
    id: 33,
    title: "El milagro de Jesucristo",
    description: "Milagro que inspira fe y asombro divino.",
    image: "/images/terminados/7.webp",
    specs: [
      "Moldura de Milán Plata con acetato plateado.",
      "Tamaños estándar",
      "Personalización disponible",
      "Materiales premium",
    ],
    details: {
      cuadro: "/images/terminados/7.webp",
    },
  },
  // "Grandes" (8 items)
  {
    id: 34,
    title: "Virgen de Guadalupe",
    description: "Cuadro grande con detalles exquisitos y acabado elegante.",
    specs: [
      "Moldura Romana Plata con rosas doradas",
      "Cuadro grande con detalles exquisitos y acabado elegante.",
      "Cuadro de acetato dorado",
    ],
    image: "/images/Grandes/1.webp",
    details: {
      cuadro: "/images/Grandes/1.webp",
    },
  },

  {
    id: 35,
    title: "Virgen de Guadalupe",
    description: "Marco grande, ornamentado con molduras de lujo.",
    specs: ["Moldura Romana Oro89", "Marco grande, ornamentado con molduras de lujo."],
    image: "/images/Grandes/2.webp",
    details: {
      cuadro: "/images/Grandes/2.webp",
    },
  },
  {
    id: 36,
    title: "Virgen de Guadalupe",
    description: "Diseño elegante en moldura grande",
    specs: ["Diseño elegante en moldura obra de arte.", "Marcos dorados y plateados"],
    image: "/images/Grandes/3.webp",
    details: {
      cuadro: "/images/Grandes/3.webp",
    },
  },
  {
    id: 37,
    title: "Virgen de Guadalupe",
    description: "Marco de gran tamaño con acabado refinado.",
    specs: ["Marco de gran tamaño con  detalles elaborados.", "Toque Moderno"],
    image: "/images/Grandes/4.webp",
    details: {
      cuadro: "/images/Grandes/4.webp",
    },
  },
  {
    id: 38,
    title: "Virgen de Guadalupe",
    description: "Cuadro grande, con toques modernos.",
    specs: ["Cuadro grande, estilo clásico", "Decorado con rosas doradas"],
    image: "/images/Grandes/5.webp",
    details: {
      cuadro: "/images/Grandes/5.webp",
    },
  },
  {
    id: 39,
    title: "Arcángel Miguel",
    description: "Detalle elegante en marco grande, ideal para piezas destacadas.",
    specs: ["Detalle elegante en marco grande, ideal para piezas destacadas.", "Moldura Romana"],
    image: "/images/Grandes/6.webp",
    details: {
      cuadro: "/images/Grandes/6.webp",
    },
  },
  {
    id: 40,
    title: "La creación de Adán",
    description: "Acabado elegante en moldura grande",
    specs: ["Acabado elegante resalta la belleza de la obra.", "Moldura Romana Oro89"],
    image: "/images/Grandes/7.webp",
    details: {
      cuadro: "/images/Grandes/7.webp",
    },
  },
  {
    id: 41,
    title: "Virgen de Guadalupe",
    description: "Cuadro grande con gran detalle",
    specs: ["Cuadro grande con gran detalle y un toque de modernidad."],
    image: "/images/Grandes/8.webp",
    details: {
      cuadro: "/images/Grandes/8.webp",
    },
  },
  // "Medianos" (10 items)
  {
    id: 42,
    title: "El Buen Pastor",
    description: "Cuadro mediano con detalles elegantes y acabado refinado.",
    specs: ["Cuadro mediano con detalles elegantes y acabado refinado."],
    image: "/images/Medianos/1.webp",
    details: {
      cuadro: "/images/Medianos/1.webp",
    },
  },
  {
    id: 43,
    title: "Virgen de Guadalupe",
    description: "Marco mediano, diseño sofisticado para realzar cualquier obra.",
    specs: ["Marco mediano, diseño sofisticado para realzar cualquier obra."],
    image: "/images/Medianos/2.webp",
    details: {
      cuadro: "/images/Medianos/2.webp",
    },
  },
  {
    id: 44,
    title: "La última cena",
    description: "Cuadro mediano, combinando tradición y modernidad.",
    specs: ["Cuadro mediano, combinando tradición y modernidad.", "Moldura Venecia"],
    image: "/images/Medianos/3.webp",
    details: {
      cuadro: "/images/Medianos/3.webp",
    },
  },
  {
    id: 45,
    title: "La última cena",
    description: "Detalle sutil en moldura mediana, con acabado elegante.",
    specs: ["Detalle sutil en moldura mediana, con acabado elegante.", "Moldura Venecia"],
    image: "/images/Medianos/4.webp",
    details: {
      cuadro: "/images/Medianos/4.webp",
    },
  },
  {
    id: 46,
    title: "Virgen de Guadalupe",
    description: "Marco mediano con un diseño pulido y sofisticado.",
    specs: ["Marco mediano con un diseño pulido y sofisticado.", "Moldura Venecia"],
    image: "/images/Medianos/5.webp",
    details: {
      cuadro: "/images/Medianos/5.webp",
    },
  },
  {
    id: 47,
    title: "Sagrado Corazón de Jesús",
    description: "Cuadro mediano, estilo contemporáneo y elegante.",
    specs: ["Cuadro mediano, estilo contemporáneo y elegante.", "Moldura Venecia"],
    image: "/images/Medianos/6.webp",
    details: {
      cuadro: "/images/Medianos/6.webp",
    },
  },
  {
    id: 48,
    title: "Virgen de Guadalupe",
    description: "Detalle ornamental en marco mediano, acabado de alta calidad.",
    specs: ["Detalle ornamental en marco mediano, acabado de alta calidad."],
    image: "/images/Medianos/7.webp",
    details: {
      cuadro: "/images/Medianos/7.webp",
    },
  },
  {
    id: 49,
    title: "Virgen de Guadalupe",
    description: "Diseño elegante en moldura mediana, con gran precisión.",
    specs: ["Diseño elegante en moldura mediana, con gran precisión."],
    image: "/images/Medianos/8.webp",
    details: {
      cuadro: "/images/Medianos/8.webp",
    },
  },
  {
    id: 50,
    title: "El milagro de Cristo",
    description: "Marco mediano, perfecto para realzar la belleza de la obra.",
    specs: ["Marco mediano, perfecto para realzar la belleza de la obra."],
    image: "/images/Medianos/9.webp",
    details: {
      cuadro: "/images/Medianos/9.webp",
    },
  },
  {
    id: 51,
    title: "El milagro de Cristo",
    description: "Cuadro mediano con un acabado impecable y detalles sutiles.",
    specs: ["Cuadro mediano con un acabado impecable y detalles sutiles.", "Moldura Romana Plata"],
    image: "/images/Medianos/10.webp",
    details: {
      cuadro: "/images/Medianos/10.webp",
    },
  },
  // "Pequeños" (14 items)
  {
    id: 52,
    title: "Cuadro pequeña, con diseño elegante y moderno.",
    description: "Cuadro pequeño, con diseño elegante y moderno.",
    specs: ["Cuadro pequeño, con diseño elegante y moderno."],
    image: "/images/Pequeños/1.webp",
    details: {
      cuadro: "/images/Pequeños/1.webp",
    },
  },
  {
    id: 53,
    title: "Virgen de Guadalupe",
    description: "Marco pequeño, detalles exquisitos en acabado dorado.",
    specs: ["Marco pequeño, detalles exquisitos en acabado dorado."],
    image: "/images/Pequeños/2.webp",
    details: {
      cuadro: "/images/Pequeños/2.webp",
    },
  },
  {
    id: 54,
    title: "Sagrado Corazón de Jesús",
    description: "Cuadro pequeño, perfecto para obras de arte íntimas.",
    specs: ["Cuadro pequeño, perfecto para obras de arte íntimas."],
    image: "/images/Pequeños/3.webp",
    details: {
      cuadro: "/images/Pequeños/3.webp",
    },
  },
  {
    id: 55,
    title: "Divina Misericordia",
    description: "Diseño moderno en moldura pequeña, con acabados de alta calidad.",
    specs: ["Diseño moderno en moldura pequeña, con acabados de alta calidad."],
    image: "/images/Pequeños/4.webp",
    details: {
      cuadro: "/images/Pequeños/4.webp",
    },
  },
  {
    id: 56,
    title: "Divina Misericordia",
    description: "Marco pequeño, estilo elegante y sofisticado.",
    specs: ["Marco pequeño, estilo elegante y sofisticado."],
    image: "/images/Pequeños/5.webp",
    details: {
      cuadro: "/images/Pequeños/5.webp",
    },
  },
  {
    id: 57,
    title: "Virgen de Guadalupe",
    description: "Cuadro pequeño con acabado dorado, realza la decoración.",
    specs: ["Cuadro pequeño con acabado dorado, realza la decoración."],
    image: "/images/Pequeños/6.webp",
    details: {
      cuadro: "/images/Pequeños/6.webp",
    },
  },
  {
    id: 58,
    title: "San Francisco de Asís",
    description: "Detalle elegante en moldura pequeña, con un toque moderno.",
    specs: ["Detalle elegante en moldura pequeña, con un toque moderno."],
    image: "/images/Pequeños/7.webp",
    details: {
      cuadro: "/images/Pequeños/7.webp",
    },
  },
  {
    id: 59,
    title: "Virgen de Guadalupe",
    description: "Marco pequeño, acabado refinado y detalle ornamental.",
    specs: ["Marco pequeño, acabado refinado y detalle ornamental."],
    image: "/images/Pequeños/8.webp",
    details: {
      cuadro: "/images/Pequeños/8.webp",
    },
  },
  {
    id: 60,
    title: "Divina Misericordia",
    description: "Cuadro pequeño, diseño minimalista y elegante.",
    specs: ["Cuadro pequeño, diseño minimalista y elegante."],
    image: "/images/Pequeños/9.webp",
    details: {
      cuadro: "/images/Pequeños/9.webp",
    },
  },
  {
    id: 61,
    title: "San Judas Tadeo",
    description: "Detalle sutil en marco pequeño, con acabado dorado.",
    specs: ["Detalle sutil en marco pequeño, con acabado dorado."],
    image: "/images/Pequeños/10.webp",
    details: {
      cuadro: "/images/Pequeños/10.webp",
    },
  },
  {
    id: 62,
    title: "Arcángel San Miguel",
    description: "Cuadro pequeño con diseño exclusivo y elegante.",
    specs: ["Cuadro pequeña con diseño exclusivo y elegante."],
    image: "/images/Pequeños/11.webp",
    details: {
      cuadro: "/images/Pequeños/11.webp",
    },
  },
  {
    id: 63,
    title: "Snan Judas Tadeo",
    description: "Marco pequeño, detalles modernos y sofisticados.",
    specs: ["Marco pequeño, detalles modernos y sofisticados."],
    image: "/images/Pequeños/12.webp",
    details: {
      cuadro: "/images/Pequeños/12.webp",
    },
  },
  {
    id: 64,
    title: "Virgen de Guadalupe",
    description: "Cuadro pequeño, perfecto para piezas de arte delicadas.",
    specs: ["Detalle pequeño, perfecta para piezas de arte delicadas."],
    image: "/images/Pequeños/13.webp",
    details: {
      cuadro: "/images/Pequeños/13.webp",
    },
  },
  {
    id: 65,
    title: "Sagrada Familia",
    description: "Detalle ornamental en moldura pequeña, con acabado de lujo.",
    specs: ["Detalle ornamental en moldura pequeña, con acabado de lujo."],
    image: "/images/Pequeños/14.webp",
    details: {
      cuadro: "/images/Pequeños/14.webp",
    },
  },
]
export const allProducts = [...placeholderTools, ...products]

export const detailsmolduras = [
  {
    id: 1,
    title: "Romana",
    description: "Romana Vino",
    image: "/images/detalles/SS/romanavinodetalle.webp",
  },
  {
    id: 2,
    title: "Romana",
    description: "Romana Nogal",
    image: "/images/detalles/SS/romananogaldetalle.webp",
  },
  {
    id: 3,
    title: "Romana",
    description: "Romana Plata",
    image: "/images/detalles/SS/romanaplatadetalle.webp",
  },
  {
    id: 4,
    title: "Romana",
    description: "Romana Oro",
    image: "/images/detalles/SS/romanaorodetalle.webp",
  },
  {
    id: 5,
    title: "Romana",
    description: "Romana Oro 89",
    image: "/images/detalles/SS/romanaoro89detalle.webp",
  },
  {
    id: 7,
    title: "florencia",
    description: "florencia vino",
    image: "/images/detalles/SS/florenciavinodetalle.webp",
  },
  {
    id: 8,
    title: "florencia",
    description: "florencia Nogal",
    image: "/images/detalles/SS/florencianogaldetalle.webp",
  },
  {
    id: 9,
    title: "florencia",
    description: "florencia Cobre",
    image: "/images/detalles/SS/florenciacobredetalle.webp",
  },
  {
    id: 10,
    title: "florencia",
    description: "florencia Plata",
    image: "/images/detalles/SS/florenciaplatadetalle.webp",
  },
  {
    id: 11,
    title: "florencia",
    description: "florencia Titanio",
    image: "/images/detalles/SS/florenciatitaniodetalle.webp",
  },
  {
    id: 12,
    title: "Venecia",
    description: "Venecia Oro",
    image: "/images/detalles/SS/florenciaveneciadetalle.webp",
  },
]
