export const placeholderTools = [
    {
    id: 2,
    title: "Laminadora en frío 650mm",
    description: "Máquina Laminadora en Frío",
    image: "/images/herramientas/laminadora1000.webp",
    specs: ["Ancho máximo de laminación 650mm"],
    Precio_unidad: 3000,
    CantXcaja: 1,
    details: {
      zoom: "/images/herramientas/laminadora1000.webp",
    },
  },
  {
    id: 3,
    title: "Laminadora en frío 750mm",
    description: "Máquina Laminadora en Frío",
    image: "/images/herramientas/laminadora650.webp",
    specs: ["Ancho máximo de laminación 750mm"],
    Precio_unidad: 3500,
    CantXcaja: 1,
    details: {
      zoom: "/images/herramientas/laminadora650.webp",
    },
  },
  {
    id: 4,
    title: "Laminadora en frío 1000mm",
    description: "Máquina Laminadora en Frío",
    image: "/images/herramientas/laminadora1000.webp",
    specs: ["Ancho máximo de laminación 10000mm"],
    Precio_unidad: 7000,
    CantXcaja: 1,
    details: {
      zoom: "/images/herramientas/laminadora1000.webp",
    },
  },
  {
    id: 6,
    title: "Engrapadora",
    description: "V-nailer, marco de imagen neumático, Joiner.",
    image: "/images/herramientas/VnailerVerde.webp",
    specs: ["Impulsa clavos en V de 7mm a 15mm", "Tiene capacidad para 200 piezas de clavos", "Solo 2,5 kg de peso"],
    Precio_unidad: 5000,
    CantXcaja: 1,
    details: {
      zoom: "/images/herramientas/VnailerVerde.webp",
    },
  },
  {
    id: 7,
    title: "Grapas flexipunta",
    description: "Grapa flexipunta",
    image: "/images/grapas/1.webp",
    specs: ["Caja con 4300 grapas", "Grapa para ensambladora de marcos", "Garantía del vendedor: 1 mes"],
    Precio_unidad: 550,
    CantXcaja: 10,
    details: {
      zoom: "/images/grapas/1.webp",
    },
  },
  {
    id: 8,
    title: "Grapas 7mm",
    description: "Grapa encolada de 7mm",
    image: "/images/grapas/2.webp",
    specs: ["Caja con 4300 grapas", "Grapa para ensambladora de marcos", "Garantía del vendedor: 1 mes"],
    Precio_unidad: 275,
    CantXcaja: 10,
    details: {
      zoom: "/images/grapas/2.webp",
    },
  },
  {
    id: 9,
    title: "Grapas 10mm",
    description: "Grapa encolada de 10mm",
    image: "/images/grapas/2.webp",
    specs: ["Caja con 4300 grapas", "Grapa para ensambladora de marcos", "Garantía del vendedor: 1 mes"],
    Precio_unidad: 275,
    CantXcaja: 10,
    details: {
      zoom: "/images/grapas/2.webp",
    },
  },
  {
    id: 10,
    title: "Grapas 12mm",
    description: "Grapa encolada de 12mm",
    image: "/images/grapas/2.webp",
    specs: ["Caja con 4300 grapas", "Grapa para ensambladora de marcos", "Garantía del vendedor: 1 mes"],
    Precio_unidad:275,
    CantXcaja: 10,
    details: {
      zoom: "/images/grapas/2.webp",
    },
  },
  {
    id: 11,
    title: "MDF",
    description: "Macocel para enmarcado",
    image: "/images/grapas/MDF.webp",
    specs: ["Medidas: 8'x10', 11'x14', 16'x20', 20'x24', 60'x90'.","Precios desde 10 hasta 70 MXN","Personalizable", "Fácil instalación", "Resistente al tiempo"],
    Precio_unidad: 40,
    CantXcaja: 1,
    details: {
      zoom: "/images/grapas/MDF.webp",
    },
  },

  {
    id: 12,
    title: "Caballete",
    description: "Caballete Pequeño",
    image: "/images/grapas/caballetepe.webp",
    specs: ["5.9inch 15cm de altura", "Tablero de fibra de madera"],
    Precio_unidad: 300,
    CantXcaja: 2,
    details: {
      zoom: "/images/grapas/caballetepe.webp",
    },
  },
  {
    id: 13,
    title: "Caballete",
    description: "Caballete Mediano",
    image: "/images/grapas/caballetemed.webp",
    specs: ["20inch 50.8cm de altura", "Tablero de madera"],
    Precio_unidad: 400,
    CantXcaja: 2,
    details: {
      zoom: "/images/grapas/caballetemed.webp",
    },
  },
  {
    id: 14,
    title: "Caballete",
    description: "Caballete Grande",
    image: "/images/grapas/caballetegran.webp",
    specs: ["59inch 150cm de altura", "Tablero de madera"],
    Precio_unidad: 500,
    CantXcaja: 1,
    details: {
      zoom: "/images/grapas/caballetegran.webp",
    },
  },
  {
    id: 15,
    title: "Cinta Adhesiva Doble Cara Más Adhesivo",
    description: "Cinta adhesiva doble cara",
    image: "/images/grapas/cintadoblecara.png",
    specs: ["Rollo un 25'x40m"],
    Precio_unidad: 1300,
    CantXcaja: 1,
    details: {
      zoom: "/images/grapas/cintadoblecara.png",
      zoom_detalle: "/images/detalles/adhesivodetalle.webp",
    },
  },
  {
    id: 16,
    title: "Cinta Adhesiva Doble Cara Más Adhesivo",
    description: "Cinta adhesiva doble cara",
    image: "/images/grapas/cintadoblecara.png",
    specs: ["Rollo un 50'x40m"],
    Precio_unidad: 2600,
    CantXcaja: 1,
    details: {
      zoom: "/images/grapas/cintadoblecara.png",
      zoom_detalle: "/images/detalles/adhesivodetalle.webp",
    },
  },
  {
    id: 17,
    title: "Rollo de Textura Piel",
    description: "Rollo de Textura Piel Más Adhesivo",
    image: "/images/herramientas/txt-ejemplo.png",
    specs: ["Rollo un 25'x40m"],
    Precio_unidad: 1300,
    CantXcaja: 1,
    details: {
      zoom: "/images/detalles/piel.webp",
      zoom_detalle: "/images/detalles/pieldetalle.webp",
      detalle2: "/images/detalles/pieldetalle1.webp",
      detalle3: "/images/detalles/pieldetalle2.webp",
      detalle4: "/images/detalles/pieldetalle3.webp",
      detalle5: "/images/detalles/pieldetalle4.webp",
    },
  },
  {
    id: 18,
    title: "Rollo de Textura Lino Fino",
    description: "Rollo de Textura Lino Fino Más Adhesivo",
    image: "/images/herramientas/txt-ejemplo.png",
    specs: ["Rollo un 25'x40m"],
    Precio_unidad: 1300,
    CantXcaja: 1,
    details: {
      zoom: "/images/detalles/linofino.webp",
      zoom_detalle: "/images/detalles/linofinodetalle.webp",
      detalle2: "/images/detalles/linoFinodetalle1.webp",
      detalle3: "/images/detalles/linoFinodetalle2.webp",
      detalle4: "/images/detalles/linoFinodetalle3.webp",
      detalle5: "/images/detalles/linoFinodetalle4.webp",
    },
  },
  {
    id: 19,
    title: "Rollo de Textura Santex",
    description: "Rollo de Textura Santex Más Adhesivo",
    image: "/images/herramientas/txt-ejemplo.png",
    specs: ["Rollo un 25'x40m"],
    Precio_unidad: 1300,
    CantXcaja: 1,
    details: {
      zoom: "/images/detalles/santex.webp",
      zoom_detalle: "/images/detalles/santexdetalle.webp",
      detalle2: "/images/detalles/santexdetalle1.webp",
      detalle3: "/images/detalles/santexdetalle2.webp",
      detalle4: "/images/detalles/santexdetalle3.webp",
      detalle5: "/images/detalles/santexdetalle4.webp",
    },
  },
  {
    id: 20,
    title: "Rollo de Textura Canvas",
    description: "Rollo de Textura Canvas Más Adhesivo",
    image: "/images/herramientas/txt-ejemplo.png",
    specs: ["Rollo un 25'x40m"],
    Precio_unidad: 1300,
    CantXcaja: 1,
    details: {
      zoom: "/images/detalles/canvas.webp",
      zoom_detalle: "/images/detalles/canvasdetalle.webp",
      detalle2: "/images/detalles/canvasdetalle1.webp",
      detalle3: "/images/detalles/canvasdetalle2.webp",
      detalle4: "/images/detalles/canvasdetalle3.webp",
      detalle5: "/images/detalles/canvasdetalle4.webp",
    },
  },  {
    id: 21,
    title: "Rollo de Textura Piel",
    description: "Rollo de Textura Piel Más Adhesivo",
    image: "/images/herramientas/txt-ejemplo.png",
    specs: ["Rollo un 50'x40m"],
    Precio_unidad: 2600,
    CantXcaja: 1,
    details: {
      zoom: "/images/detalles/piel.webp",
      zoom_detalle: "/images/detalles/pieldetalle.webp",
      detalle2: "/images/detalles/pieldetalle1.webp",
      detalle3: "/images/detalles/pieldetalle2.webp",
      detalle4: "/images/detalles/pieldetalle3.webp",
      detalle5: "/images/detalles/pieldetalle4.webp",
    },
  },
  {
    id: 22,
    title: "Rollo de Textura Lino Fino",
    description: "Rollo de Textura Lino Fino Más Adhesivo",
    image: "/images/herramientas/txt-ejemplo.png",
    specs: ["Rollo un 50'x40m"],
    Precio_unidad: 2600,
    CantXcaja: 1,
    details: {
      zoom: "/images/detalles/linofino.webp",
      zoom_detalle: "/images/detalles/linofinodetalle.webp",
      detalle2: "/images/detalles/linoFinodetalle1.webp",
      detalle3: "/images/detalles/linoFinodetalle2.webp",
      detalle4: "/images/detalles/linoFinodetalle3.webp",
      detalle5: "/images/detalles/linoFinodetalle4.webp",
    },
  },
  {
    id: 23,
    title: "Rollo de Textura Santex",
    description: "Rollo de Textura Santex Más Adhesivo",
    image: "/images/herramientas/txt-ejemplo.png",
    specs: ["Rollo un 50'x40m"],
    Precio_unidad: 2600,
    CantXcaja: 1,
    details: {
      zoom: "/images/detalles/santex.webp",
      zoom_detalle: "/images/detalles/santexdetalle.webp",
      detalle2: "/images/detalles/santexdetalle1.webp",
      detalle3: "/images/detalles/santexdetalle2.webp",
      detalle4: "/images/detalles/santexdetalle3.webp",
      detalle5: "/images/detalles/santexdetalle4.webp",
    },
  },
  {
    id: 24,
    title: "Rollo de Textura Canvas",
    description: "Rollo de Textura Canvas Más Adhesivo",
    image: "/images/herramientas/txt-ejemplo.png",
    specs: ["Rollo un 50'x40m"],
    Precio_unidad: 2600,
    CantXcaja: 1,
    details: {
      zoom: "/images/detalles/canvas.webp",
      zoom_detalle: "/images/detalles/canvasdetalle.webp",
      detalle2: "/images/detalles/canvasdetalle1.webp",
      detalle3: "/images/detalles/canvasdetalle2.webp",
      detalle4: "/images/detalles/canvasdetalle3.webp",
      detalle5: "/images/detalles/canvasdetalle4.webp",
    },
  },
]

export const products = [
  {
    id: 25,
    title: "Romana",
    description: "Moldura Exclusiva de Romana Centro",
    image: "/images/molduras/romana.webp",
    specs: ["Colores: Vino, Nogal, Plata, Oro, Oro 89", "Cortada a medida", "Barra entera (2.9m)", "Poliestireno"],
    Precio_unidad: 120,
    CantXcaja: 20,
    details: {
      vino: "/images/detalles/romanavino.webp",
      vino_detalle: "/images/detalles/romanavinodetalle.webp",
      nogal: "/images/detalles/romananogal.webp",
      nogal_detalle: "/images/detalles/romananogaldetalle.webp",
      plata: "/images/detalles/romanaplata.webp",
      plata_detalle: "/images/detalles/romanaplatadetalle.webp",
      oro: "/images/detalles/romanaoro.webp",
      oro_detalle: "/images/detalles/romanaorodetalle.webp",
      oro89: "/images/detalles/romanaoro89.webp",
      oro89_detalle: "/images/detalles/romanaoro89detalle.webp",
    },
  },
  {
    id: 26,
    title: "florencia",
    description: "Moldura para enmarcado de alta resistencia",
    image: "/images/molduras/florencia.JPG",
    specs: ["Colores: Plata, Vino, Nogal, Cobre, Titanio ", "Cortada a medida", "Barra entera (2.9m)", "Poliestireno"],
    Precio_unidad: 120,
    CantXcaja: 17,
    details: {
      vino: "/images/detalles/florenciavino.webp",
      vino_detalle: "/images/detalles/florenciavinodetalle.webp",
      nogal: "/images/detalles/florencianogal.webp",
      nogal_detalle: "/images/detalles/florencianogaldetalle.webp",
      cobre: "/images/detalles/florenciacobre.webp",
      cobre_detalle: "/images/detalles/florenciacobredetalle.webp",
      titanio: "/images/detalles/florenciatitanio.webp",
      titanio_detalle: "/images/detalles/florenciatitaniodetalle.webp",
      plata: "/images/detalles/florenciaplata.webp",
      plata_detalle: "/images/detalles/florenciaplatadetalle.webp",
    },
  },
  {
    id: 27,
    title: "Nápoles",
    description: "Moldura para enmarcado de alta resistencia",
    image: "/images/molduras/napoles.webp",
    specs: ["Colores: Negro, Chocolate, Vino, Nogal,Titanio", "Barra entera (2.9m)", "Poliestireno"],
    Precio_unidad: 120,
    CantXcaja: 24,
    details: {
      negro: "/images/detalles/napolesnegro.webp",
      negro_detalle: "/images/detalles/napolesnegrodetalle.webp",
      chocolate: "/images/detalles/napoleschocolate.webp",
      chocolate_detalle: "/images/detalles/napoleschocolatedetalle.webp",
      vino: "/images/detalles/napolesvino.webp",
      vino_detalle: "/images/detalles/napolesvinodetalle.webp",
      nogal: "/images/detalles/napolesnogal.webp",
      nogal_detalle: "/images/detalles/napolesnogaldetalle.webp",
      titanio: "/images/detalles/napolestitanio.webp",
      titanio_detalle: "/images/detalles/napolestitaniodetalle.webp",
    },
  },
  {
    id: 28,
    title: "Milán",
    description: "Moldura para enmarcado de alta resistencia",
    image: "/images/molduras/milan.webp",
    specs: ["Colores: Negro, Plata, Bronce", "Barra entera (2.9m)", "Poliestireno"],
    Precio_unidad: 100,
    CantXcaja: 34,
    details: {
      negro: "/images/detalles/milannegro.webp",
      negro_detalle: "/images/detalles/milannegrodetalle.webp",
      plata: "/images/detalles/milanplata.webp",
      plata_detalle: "/images/detalles/milanplatadetalle.webp",
      bronce: "/images/detalles/milanbronce.webp",
      bronce_detalle: "/images/detalles/milanbroncedetalle.webp",
    },
  },
  {
    id: 29,
    title: "Lazio",
    description: "Moldura para enmarcado de alta resistencia",
    image: "/images/molduras/Lazio.jpg",
    specs: ["Colores: Negro, Plata, Chocolate, Nogal, Oro", "Cortada a medida", "Barra entera (2.9m)", "Poliestireno"],
    Precio_unidad: 55,
    CantXcaja: 100,
    details: {
      nogaloscuro: "/images/detalles/Laziodetallenogaloscuro.jpg",
      nogal: "/images/detalles/Laziodetallenogall.jpg",
      negro: "/images/detalles/Laziodetallenegro.jpg",
      oro: "/images/detalles/Laziodetalleoro.jpg",
      plata: "/images/detalles/Laziodetalleplata.jpg",
    },
  },
]


export const allProducts = [...placeholderTools, ...products]

export const detailsmolduras = [
  {
    id: 1,
    title: "Romana",
    description: "Romana Vino",
    image: "/images/detalles/SS/romanavinodetalle.webp",
  },
  {
    id: 2,
    title: "Romana",
    description: "Romana Nogal",
    image: "/images/detalles/SS/romananogaldetalle.webp",
  },
  {
    id: 3,
    title: "Romana",
    description: "Romana Plata",
    image: "/images/detalles/SS/romanaplatadetalle.webp",
  },
  {
    id: 4,
    title: "Romana",
    description: "Romana Oro",
    image: "/images/detalles/SS/romanaorodetalle.webp",
  },
  {
    id: 5,
    title: "Romana",
    description: "Romana Oro 89",
    image: "/images/detalles/SS/romanaoro89detalle.webp",
  },
  {
    id: 7,
    title: "florencia",
    description: "florencia vino",
    image: "/images/detalles/SS/florenciavinodetalle.webp",
  },
  {
    id: 8,
    title: "florencia",
    description: "florencia Nogal",
    image: "/images/detalles/SS/florencianogaldetalle.webp",
  },
  {
    id: 9,
    title: "florencia",
    description: "florencia Cobre",
    image: "/images/detalles/SS/florenciacobredetalle.webp",
  },
  {
    id: 10,
    title: "florencia",
    description: "florencia Plata",
    image: "/images/detalles/SS/florenciaplatadetalle.webp",
  },
  {
    id: 11,
    title: "florencia",
    description: "florencia Titanio",
    image: "/images/detalles/SS/florenciatitaniodetalle.webp",
  },
  {
    id: 12,
    title: "Venecia",
    description: "Venecia Oro",
    image: "/images/detalles/SS/florenciaveneciadetalle.webp",
  },
]
